version: '3.8'

services:
  payload:
    image: node:18-alpine
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "npm install && npm run dev"
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      - NODE_ENV=development

  mongo:
    image: mongo:7.0
    restart: always
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_DATABASE=payload-example-multi-tenant
    volumes:
      - mongo_data:/data/db
    command:
      - --storageEngine=wiredTiger
    logging:
      driver: none

volumes:
  mongo_data:
  node_modules:
